### ISSUE TITLE
Help using the civicSip on Client side in React app

### ISSUE THREAD

**Issue by devssh** [civicteam/npm-civic-sip-api#13]
So the civic documentation suggests using <script src="https://hosted-sip.civic.com/js/civic.sip.min.js"> tag to load the civic global variable but I am unable to access it.
Further the civic-sip-api module needs the private keys to create a constructor which is not really good data to have on the client side of user's browser.
This module is technically the server side for the jwt token access.

Any ideas on how to get around this or an example application in react?

**Comment by slaphead** [comment]
Hi Devssh, the script should be loaded at the top level of the body where you need to access the global. civic should be accessible then. If this is the case, could you perhaps share some relevant lines so we can have a look further why it is not available.

The API module should only be run on the server side where the keys are used. It is a node.js module. The client(browser) only passes the jwt token back to the server on event auth-code-received. Server side then does exchange code with the jwt token using the constructor.

Perhaps we made it slightly confusing by calling the function for the object 'newClient'. What we meant here is that this is a newClient for exchanging the code and getting the user data.

This part
```
const civicClient = civicSip.newClient({
  appId: 'CO-ABCDEFG1230934545',
  prvKey: PRIVATE_KEY,
  appSecret: APP_SECRET,
});
```

Should only be used on the server side. The terminology might be a bit misleading here.

Let me know if this helps.

**Comment by devssh** [comment]
Here is the code 

```
import React from 'react';

const CivicLogin = () => {
    civiccSip.on('auth-code-received', function (event) {
        /*
            event:
            {
                event: "scoperequest:auth-code-received",
                response: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJqdGkiOiI2Y2EwNTEzMi0wYTJmLTQwZjItYTg2Yi03NTkwYmRjYzBmZmUiLCJpYXQiOjE0OTQyMjUxMTkuMTk4LCJleHAiOjE0OTQyMjUyOTkuMTk4LCJpc3MiOiJjaXZpYy1zaXAtaG9zdGVkLXNlcnZpY2UiLCJhdWQiOiJodHRwczovL3BoNHg1ODA4MTUuZXhlY3V0ZS1hcGkudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vZGV2Iiwic3ViIjoiY2l2aWMtc2lwLWhvc3RlZC1zZXJ2aWNlIiwiZGF0YSI6eyJjb2RlVG9rZW4iOiJjY2E3NTE1Ni0wNTY2LTRhNjUtYWZkMi1iOTQzNjc1NDY5NGIifX0.gUGzPPI2Av43t1kVg35diCm4VF9RUCF5d4hfQhcSLFvKC69RamVDYHxPvofyyoTlwZZaX5QI7ATiEMcJOjXRYQ",
                type: "code"
            }
        */

        // encoded JWT Token is sent to the server
        const jwtToken = event.response;

        // Your function to pass JWT token to your server
        //sendAuthCode(jwtToken);
        console.log('jwt', jwtToken)
    });

    civicSip.on('user-cancelled', function (event) {
        /*
            event:
            {
              event: "scoperequest:user-cancelled"
            }
        */
    });

    civicSip.on('read', function (event) {
        /*
            event:
            {
              event: "scoperequest:read"
            }
        */
    });

    // Error events.
    civicSip.on('civic-sip-error', function (error) {
        // handle error display if necessary.
        console.log('   Error type = ' + error.type);
        console.log('   Error message = ' + error.message);
    });
    return (
        <div>
            <link rel="stylesheet" href="https://hosted-sip.civic.com/css/civic-modal.min.css"/>
            <script src="https://hosted-sip.civic.com/js/civic.sip.min.js"/>
            <button id="signupButton" className="civic-button-a medium" type="button"
                //         onClick={() => {
                //     civicSip.signup({style: 'popup', scopeRequest: civicSip.ScopeRequests.BASIC_SIGNUP})
                // }}
            >
                <span>Log in with Civic</span>
            </button>
            {renderEvents()}
        </div>
    );
};

export default CivicLogin;

```

I have tried moving it around but it cant detect the civic object in the renderings of the component
I have even tried [](https://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx)
to no success. It seems you need a npm module to import objects and global objects are hard if not impossible.

**Comment by devssh** [comment]
I downloaded the hosted civic.sip.min.js as a file and put it in source, disabled eslint, imported civic from the file and got this error again. I confirmed the appid and civic object were there.

TypeError: __WEBPACK_IMPORTED_MODULE_1__civic_sip_min___default.a.sip is not a constructor
CivicLogin
src/CivicLogin.js:6
  3 | 
  4 | const CivicLogin = () => {
  5 |     console.log(civic, "civic");
> 6 |     let civicSip = new civic.sip({ appId: process.env.REACT_APP_APPID });
  7 | 
  8 |     civicSip.on('auth-code-received', function (event) {
  9 |         /*

**Comment by devssh** [comment]
Please help integrating the "Login with Civic" button in React... Could you do a sample application for the same in React and publish to github? 
It would be so much better than having to integrate oauth2 or my own integration logic via SMTP servers for email and Message queues for SMS.

**Comment by stewart42** [comment]
Hi @devssh 

Downloading the civic.sip.min.js is not advised as we often update the library. 
We strongly recommend having the following in your html
```
<link rel="stylesheet" href="https://hosted-sip.civic.com/css/civic-modal.min.css">

<script src="https://hosted-sip.civic.com/js/civic.sip.min.js"></script>
```
From your sample of code I am not sure where are initializing the `civicSip` variable, something like:
```
  var civicSip = new civic.sip({ appId: 'ABC123' });

**Comment by devssh** [comment]
Hi stewart, I have simplified my code to illustrate the exact problem in a consise way, the rest of the code is the default code generated by the create-react-app bootstrapper

import React from 'react';

```
const CivicLoginButton = () => {
return (
        <div>
            <link rel="stylesheet" href="https://hosted-sip.civic.com/css/civic-modal.min.css"/>
            <script src="https://hosted-sip.civic.com/js/civic.sip.min.js"/> // this line does not load the civic global variable which is used to create the civicSip variable as you have shown.
            <button id="signupButton" className="civic-button-a medium" type="button"
                //         onClick={() => {
                //     civicSip.signup({style: 'popup', scopeRequest: civicSip.ScopeRequests.BASIC_SIGNUP})
                // }}
            >
                <span>Log in with Civic</span>
                //{console.log(civic, 'civic')}
            </button>
            {renderEvents()}
        </div>
    );
};

export default CivicLoginButton;
```

**Comment by IanKemp** [comment]
As @stewart42 mentioned, you need to put those tags in the <head> of your HTML file. You can't include scripts inside a React component.

```
<link rel="stylesheet" href="https://hosted-sip.civic.com/css/civic-modal.min.css"/>
<script src="https://hosted-sip.civic.com/js/civic.sip.min.js"/>
```

**Comment by devssh** [comment]
Thank you so much! It works now
