### ISSUE TITLE
How to exchange userData?

### ISSUE THREAD

**Issue by kingstenbanh** [civicteam/npm-civic-sip-api#14]
Hi @slaphead, 

The Civic project is pretty amazing. I love that I have the control of my identity instead of some third party. I want to build some application with the SDK. However, I am running into some issue with exchange `jwtToken` with the server. Here are my codes. Please help!

`index.html` (Client)
https://gist.github.com/kingstenbanh/f60357f7c69350eaaedb63745c6c061c

`app.js` (Server)
https://gist.github.com/kingstenbanh/93962392cf42c3f91de3095dab4de7a4

### Civic Integrate Config
<img width="1574" alt="screen shot 2018-01-08 at 12 30 17 am" src="https://user-images.githubusercontent.com/7540669/34662066-27189380-f40b-11e7-896c-c122f40392ca.png">

### Error Output
```
Magic happens on port 8080
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmYzQ3Yzg0NS0xZDI1LTQxNTktOGM2OS03ZjU5YjkyNzMzYTIiLCJpYXQiOjE1MTUzOTY3MTUuNTk1LCJleHAiOjE1MTUzOTg1MTUuNTk1LCJpc3MiOiJjaXZpYy1zaXAtaG9zdGVkLXNlcnZpY2UiLCJhdWQiOiJodHRwczovL2FwaS5jaXZpYy5jb20vc2lwLyIsInN1YiI6IlMxRlhPSTFFRyIsImRhdGEiOnsiY29kZVRva2VuIjoiNmRiZTY2MGQtZTI2YS00M2JmLTljNTMtODIwMGY1ZDFjNGRlIn19.wXEqKYuVoHu5w7u31yHZV-geXbeDJjZmgMhn4OtB9pdE5Ra199hxdzvWVhf1q41c2QT3GtLVywAwJUtb1cQCDQ
HEYHEY Error: 401 Unauthorized
    at needle.then (/Users/kingstenbanh/Documents/Projects/Learning/TestCivic/node_modules/civic-sip-api/index.js:149:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
error Error: Error exchanging code for data: 401 Unauthorized
    at needle.then.catch (/Users/kingstenbanh/Documents/Projects/Learning/TestCivic/node_modules/civic-sip-api/index.js:168:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
express deprecated res.send(body, status): Use res.status(status).send(body) instead app.js:37:21
```

**Comment by stewart42** [comment]
Hi @kingstenbanh 

The client and server are using different appId's. The appId in the app.js should be `S1FXOI1EG`. 

Please note once you have got it working, please regenerate your keys or make a new app as your secret and private key is in the gist.

**Comment by kingstenbanh** [comment]
Hi @stewart42,

Thank you for spot-checking for me! It WORKS! I was hitting the wall last night trying to make the server works. I have to say the "SDK is super to use". Very impressive works 👍 

I see on the Civic website that Civic ID could potentially act as our government issued ID (name, dob). However, the app only has phone # and email address. Can you provide some info on when the feature becomes available? or I am missing something from the SDK.

**Comment by stewart42** [comment]
Great, happy you got it up and running.

Sadly I can not provide any further details right now, however, keep an eye on our [website](https://www.civic.com/products/civic-marketplace) as we will be announcing new product features there. There is also a high-level roadmap for some of the significant features planned.

**Comment by kyjadhav** [comment]
Hi @kingstenbanh , I tried consuming the API in the same way as you did. 
I changed App Id, private key and secret key of my application.
But when I click on Log In button, I get following error

![capture2](https://user-images.githubusercontent.com/37531170/41768737-beff1f9c-762a-11e8-9426-02b8f7caa515.PNG)
