### ISSUE TITLE
Error: Error exchanging code for data: Error: JWT Token containing encrypted data could not be verified at verifyAndDecrypt 

### ISSUE THREAD

**Issue by arjunuk** [civicteam/npm-civic-sip-api#28]
Hi,
I'm using **civic-sip-api** in a Node.Js app for login and every thing was working fine. But today when I tried to login using civic, got the following error.

Error: Error exchanging code for data: Error: JWT Token containing encrypted data could not be verified at verifyAndDecrypt (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\civic-sip-api\dist\index.js:248:13) at Object._callee$ (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\civic-sip-api\dist\index.js:83:48) at tryCatch (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\regenerator-runtime\runtime.js:62:40) at Generator.invoke [as _invoke] (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\regenerator-runtime\runtime.js:296:22) at Generator.prototype.(anonymous function) [as next] (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\regenerator-runtime\runtime.js:114:21) at step (E:\Projects\BASaaS\branches\dios_phase_2\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30) at E:\Projects\BASaaS\branches\dios_phase_2\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13 at at process._tickCallback (internal/process/next_tick.js:182:7)

Any help would be greatly appreciated. Thank you.

**Comment by slaphead** [comment]
It looks like the jwt token was not valid and therefore could not get verified. This looks like a possible implementation issue. Please could you log a ticket with civic@support.com so we can track this one as it does not appear to be a code issue with the repo.

Thank you!

**Comment by arjunuk** [comment]
Ok, thank you.
