### ISSUE TITLE
getting TypeError - TypeError: civicSip.newClient is not a function

### ISSUE THREAD

**Issue by sarBolt** [civicteam/npm-civic-sip-api#33]
I know that currently Civic API is only supporting nodeJS 6.10.x - though I am running on version 8.12.0 - I assume that it caused the error above?

Is there a plan to support later version of Node, or is there a REST API or some sort to get around this?

**Comment by slaphead** [comment]
Hi sarBolt,

We have it working with node 8 implementations. The minimum version should be node 6.

Do you have a code snippet to share where you are getting the error?

Right now we do not have plans to make it a REST API as the secret used to decrypt the data is best not to be passed outside your server. Therefore the library needs to assist with this.

**Comment by sarBolt** [comment]
Hi slaphead,

Thank you for your prompt reply.

I am using Meteor (https://www.meteor.com) as my framework, which currently running nodeJS 8.12.0. 

I am using ES6 to create JS classes, here is the snippet, I basically copied from the Civic example:

```
let _civicClient = civicSip.newClient({
            appId: 'MY_APPID',
            prvKey: 'MY_PRIVATE_KEY,
            appSecret: 'MY_APP_SEC'
        });

        _civicClient.exchangeCode(jwtToken)
            .then((userData) => {
                // store user data and userId as appropriate
                console.log(userData);
            }).catch((error) => {
            console.log(error);
        });
```

Although, when I installed the api via npm, it complaint that I need to install the dependencies manually, which I did (the effecting dep is chai) - not sure if it is due to this?

Here is the output;

```
exception while invoking method 'updateUserProfileBasicCivicVerification' TypeError: civicSip.newClient is not a function
```

**Comment by sarBolt** [comment]
I decided to remove the api and reinstall. now it is working!
I hope you didn't spend too much time looking into this.. my apologies! though it is good to know that the api works with node 8.
