### ISSUE TITLE
The server responded with a status of 401

### ISSUE THREAD

**Issue by florananda** [civicteam/npm-civic-sip-api#37]
Hi,
I am trying to integrate Civic identity in a node.js application. I am running the application in TEST mode.
However while invoking the login ("BASIC SIGNUP") event it is throwing "Failed to load resource: the server responded with a status of 401 (Unauthorized).
api.civic.com/sip/prod/scopeRequest/qrcode:1"

This is just the login button. Code below:

<!DOCTYPE html>
<html>
<head>
 
    <title>Login Page</title>
	<link rel="stylesheet" href="https://hosted-sip.civic.com/css/civic-modal.min.css">
    

</head>
    <body>
         <button id="signupButton" class="civic-button-a medium" type="button">
			<span>Log in with Civic</span>
		 </button>
        
    </body>
	<script  src="https://hosted-sip.civic.com/js/civic.sip.min.js"></script>
    <script>
			var civicSip = new civic.sip({ appId: 'JTfdg1OQX' });
			var button = document.getElementById('signupButton');
			button.addEventListener('click', function () {
			civicSip.signup({ style: 'popup', scopeRequest: civicSip.ScopeRequests.BASIC_SIGNUP });
			});
			 // Listen for data
			civicSip.on('auth-code-received', function (event) {
				// encoded JWT Token is sent to the server
				var jwtToken = event.response;

				// Your function to pass JWT token to your server
				sendAuthCode(jwtToken);
			  });
			 civicSip.on('user-cancelled', function (event) {
				/*
					event:
					{
					  event: "scoperequest:user-cancelled"
					}
				*/
			   });

			  civicSip.on('read', function (event) {
				/*
					event:
					{
					  event: "scoperequest:read"
					}
				*/
			  });

			   // Error events.
			   civicSip.on('civic-sip-error', function (error) {
				  // handle error display if necessary.
				  console.log('   Error type = ' + error.type);
				  console.log('   Error message = ' + error.message);
			   });  
    </script>
</html>

**Comment by slaphead** [comment]
Hi Flora,

Please can you log this as a ticket with support@civic.com. We can assist you from there as this looks more like an implementation question as opposed to a bug in code. Also, this question is in relation to the front end and not npm-civic-sip-api.

We will respond a bit quicker as well from the support channel. :)
