### ISSUE TITLE
CivicSip error parsing event data.

### ISSUE THREAD

**Issue by vol4tim** [civicteam/npm-civic-sip-api#40]
I get the error "Error parsing event data: text ..."

We use a metamask extension (https://metamask.io/) for an application that sends messages window.postMessage. CivicSip gives an error on them.
Metamask itself periodically sends such messages. For this reason, it cannot be used CivicSip with this extension.

To reproduce this problem, you can send any message.

`window.postMessage("hello there!", "*");`

![Выделение_169](https://user-images.githubusercontent.com/14287968/57834144-b0843980-77cc-11e9-8b79-fd858e9b2fdd.png)

**Comment by slaphead** [comment]
Thank you for posting this! We have a ticket to look into this and will report back

**Comment by slaphead** [comment]
Just a note, this issue is related to the other repo:
https://github.com/civicteam/civic-sip-js/pull/56

That is the PR with the fix. We are currently testing this

**Comment by slaphead** [comment]
@vol4tim There is a fix out now. Please let us know if things are all ok your side? The cache should have been cleared, but if you have issues still, please also test after doing a hard reload on the browser.

**Comment by vol4tim** [comment]
Thank you very much. The problem is gone.
