### ISSUE TITLE
babel-polyfill replaces existing Promise implementation

### ISSUE THREAD

**Issue by adrian-gierakowski** [civicteam/npm-civic-sip-api#5]
same as: https://github.com/feathersjs/feathers/issues/510

it is very well described in the above issue so I will not repeat it here ( it would suffice to copy and paste replacing `feathers` with `civic-sip-api` )

for others needing a workaround util this is resolved, replace:

```js
global.Promise = require("bluebird")
```

with 

```js
Object.defineProperty(global, "Promise", {
  value:require("bluebird"),
  writable:false
})
```

**Comment by slaphead** [comment]
Thanks for giving the background here. Busy looking into.

**Comment by slaphead** [comment]
Updated to use babel-runtime to stop polluting globals.
